---
- hosts: bigip-managers
  #hardcode now but eventually pass it in as read through master VIP/Application DB/List.
  vars:
    vip_id: 1
  #Grab Interface IDs and Secondary IPs from each BIGIP
  vars_files:
     - "~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.yml"
  gather_facts: no
  tasks:
    - name: deploy eips
      include: "{{ install_path }}/roles/infra/tasks/deploy_eip.yml"


