---
- hosts: bigip-managers
  gather_facts: no
  tasks:
    - name: deploy bigips
      include: "{{ install_path }}/roles/infra/tasks/deploy_bigip.yml"

- hosts: bigips
  gather_facts: no
  roles:
    # basic devic setup: admin users, ntp, dns, dhcp, snmp, db keys, etc.
    - bigip_base 

- hosts: bigips
  gather_facts: no
  roles:
  # vlans, self-ips, gateway_pools, routes
    - bigip_network

- hosts: bigips
  gather_facts: no
  roles:
    # add python json/simplejson for use with ansible
    #- bigip_jsonify
