---
- name: Deploying/updating webserver pool
  delegate_to: localhost
  bigip_config:
      name="Deploying/updating webserver pool"
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      payload='{{lookup('file', '~/vars/f5aws/env/' + env_name + '/' + vip_id + '_pool_from_containers.json')}}'
      collection_path='mgmt/tm/ltm/pool'
      resource_key="name"

- name: Uploading iRules ... irule_random_snat
  delegate_to: localhost
  bigip_config:
      name="Uploading iRules ... irule_random_snat"
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/ltm/rule'
      resource_key="name"
      payload='{"name":"irule_random_snat","apiAnonymous":"{{irule_random_snat|replace("\\","\\\\")|replace("\"","\\\"")|replace("\n","\\n")}}"}'

- name: Setup the HTTP virtual server
  delegate_to: localhost
  bigip_config:
      name="Setup the HTTP virtual server"
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/ltm/virtual'
      resource_key="name"
      payload='{"name":"{{vip_id}}_http","destination":"/Common/{{VipAddress2}}:80","mask":"255.255.255.255","ipProtocol":"tcp","pool":"/Common/{{vip_id}}_pool","translateAddress":"enabled","translatePort":"enabled","sourceAddressTranslation":{"type":"automap"},"rules":["/Common/irule_random_snat"], "profiles":[{"name":"http"},{"name":"tcp-wan-optimized","context":"clientside"},{"name":"tcp-lan-optimized","context":"serverside"}]}'

- name: Setup the HTTPS virtual server
  delegate_to: localhost
  bigip_config:
      name="Setup the HTTPS virtual server"
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/ltm/virtual'
      resource_key="name"
      payload='{"name":"{{vip_id}}_https","destination":"/Common/{{VipAddress2}}:443","mask":"255.255.255.255","ipProtocol":"tcp","pool":"/Common/{{vip_id}}_pool","translateAddress":"enabled","translatePort":"enabled","sourceAddressTranslation":{"type":"automap"},"rules":["/Common/irule_random_snat"], "profiles":[{"name":"tcp-ssl-wan-optimized","context":"clientside"},{"name":"tcp-ssl-lan-optimized","context":"serverside"}]}'
