---
# networking defaults
vpc_cidr_prefix: "172.16"
containers_per_host: 2
apphosts_per_zone: 1


# default ami is ECS-Optimized AMI
# https://aws.amazon.com/marketplace/pp/B00U6QTYI2
# Using 2015.03.f

# some variables for our more complex deployment models

standalone_per_zone:
  clustering: none
  bigips_per_zone: 1
  gtms_per_zone: 1

cluster_per_zone:
  clustering: same-az
  bigips_per_zone: 2
  gtms_per_zone: 1


