---

# ---------------------------------
# AWS-specific system variables
# ---------------------------------

- name: Set aws access and secret keys
  delegate_to: localhost
  bigip_config:
    state=present
    host={{ inventory_hostname }}
    user={{ bigip_rest_user }}
    password={{ bigip_rest_pass }}
    payload='{"awsAccessKey":"5678", "awsSecretKey":"5678"}'
    collection_path='mgmt/tm/sys/global-settings'

- name: Disable dhcp
  delegate_to: localhost
  bigip_config:
    state=present
    host={{ inventory_hostname }}
    user={{ bigip_rest_user }}
    password={{ bigip_rest_pass }}
    payload='{ "value":"disable" }'
    collection_path='mgmt/tm/sys/db/dhclient.mgmt'


