---
# if we are deploying a WAF as part of our BIG-IP config, 
#  we need the BEST license and asm to be provisioned after boot
- include: provision_inventory.yml
  vars:
      bigip_license_type: best
      bigip_modules: 
       - avr
       - asm
  when: deploy_waf is defined and deploy_waf == "true"

- include: provision_inventory.yml
  when: deploy_waf is undefined or deploy_waf == "false"