---
# Create the directory structure for this deployment
- file: path="~/vars/f5aws/env/{{ env_name }}" state="directory"
- file: path="~/vars/f5aws/env/{{ env_name }}/inventory" state="directory"
- file: path="~/vars/f5aws/env/{{ env_name }}/inventory/host_vars" state="directory"
- file: path="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars" state="directory"

# Creating group_vars files for 'localhosts'

- file: path="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/apphosts" state="touch"
- template: src="group_vars_localhosts.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/localhosts"

# Adding group vars for dynamic groups that will be provisioned
- template: src="group_vars_clients.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/clients"
- template: src="group_vars_apphosts.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/apphosts"
- template: src="group_vars_bigips.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/bigips"
- template: src="group_vars_gtms.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/gtms"
- template: src="group_vars_analyticshosts.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/group_vars/analyticshosts"

# Adding hosts file from template
- template: src="hosts-{{ deployment_model }}.j2" dest="~/vars/f5aws/env/{{ env_name }}/inventory/hosts"

# if we are deploying a WAF as part of our BIG-IP config, 
#  we need the BEST license and asm to be provisioned after boot
- include: provision_inventory.yml
  vars:
      bigip_license_package: best
      bigip_modules: 
       - avr
       - asm
  when: deployment_type == "lb_and_waf"

- include: provision_inventory.yml
  when: deployment_type == "lb_only"
