- name: Deploying/updating Webserver Pool
  delegate_to: localhost
  bigip_config:
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      payload='{{lookup('file', '~/vars/f5aws/env/' + env_name + '/' + vip_id + '_pool_from_containers.json')}}'
      collection_path='mgmt/tm/ltm/pool'
      resource_key="name"

- name: Deploying/updating High Speed Logging pool to send to Analytics Server
  delegate_to: localhost
  bigip_config:
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/ltm/pool'
      resource_key="name"
      payload='{"name":"syslog_pool","members":[{"name":"10.0.3.32:514","address":"10.0.3.32"},{"name":"10.0.3.33:514","address":"10.0.3.33"}],"monitor":"tcp"}' 

##### UPLOAD DATAGROUP #####
# TODO:
# "Setting SSL Profiles"
# "Setting Remote Logging Profiles"

- name: Deploying/updating Analytics Profile
  delegate_to: localhost
  bigip_config:
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/ltm/profile/analytics'
      resource_key="name"
      payload='{"name":"demo_analytics_profile","capturedTrafficExternalLogging":"disabled","capturedTrafficInternalLogging":"disabled","collectGeo":"enabled","collectIp":"enabled","collectMaxTpsAndThroughput":"enabled","collectMethods":"enabled","collectPageLoadTime":"enabled","collectResponseCodes":"enabled","collectSubnets":"enabled","collectUrl":"enabled","collectUserAgent":"enabled","collectUserSessions":"enabled","collectedStatsExternalLogging":"disabled","collectedStatsInternalLogging":"enabled","defaultsFrom":"/Common/analytics","notificationByEmail":"disabled","notificationBySnmp":"disabled","notificationBySyslog":"disabled","partition":"Common","publishIruleStatistics":"disabled","sampling":"enabled","sessionCookieSecurity":"ssl-only","sessionTimeoutMinutes":"5"}'

- name: Uploading Datagroup ... background for sorry page
  delegate_to: localhost
  bigip_config:
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/ltm/data-group/internal'
      resource_key="name"
      payload='{"name":"background_images","type":"string","records":[{"name":"{{image_background}}"}]}'

- name: Uploading Datagroup ... image for sorry page
  delegate_to: localhost
  bigip_config:
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/ltm/data-group/internal'
      resource_key="name"
      payload='{"name":"sorry_images","type":"string","records":[{"name":"{{image_sorry}}"}]}'

- name: Uploading iRules ... sorry_page_rule
  delegate_to: localhost
  bigip_config:
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/ltm/rule'
      resource_key="name"
      payload='{"name":"irule_sorry_page","apiAnonymous":"{{irule_sorry_page|replace("\\","\\\\")|replace("\"","\\\"")|replace("\n","\\n")}}"}'

- name: Uploading iRules ... demo_analytics_rule
  delegate_to: localhost
  bigip_config:
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/ltm/rule'
      resource_key="name"
      payload='{"name":"irule_demo_analytics","apiAnonymous":"{{irule_demo_analytics|replace("\\","\\\\")|replace("\"","\\\"")|replace("\n","\\n")}}"}'

# - include: provision_waf_depends.yml
#   when: deployment_type == "lb_and_waf"

- debug: var=ltm_policy_name

# Generate the iApp we will deploy from a template 
- name: Modify iApp to use VipAddress
  template: src='{{ install_path }}/roles/bigip_app1/templates/iapp_f5_http_backport_service.json.j2' dest='~/vars/f5aws/env/{{ env_name }}/iapp_f5_http_backport_service-{{ vip_id }}.json'
  delegate_to: localhost

- name: Deploy the iApp template, since we are not using a default iApp on box
  delegate_to: localhost
  bigip_config:
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/sys/application/template'
      payload_file="{{ install_path }}/roles/bigip_app1/files/iapp_f5_http_backport_template.json"
      resource_key="name"

- name: Deploy the iApp service
  delegate_to: localhost
  bigip_config:
      state=present
      host={{ ansible_ssh_host }}
      user={{ bigip_rest_user }}
      password={{ bigip_rest_password }}
      collection_path='mgmt/tm/sys/application/service'
      payload_file="~/vars/f5aws/env/{{ env_name }}/iapp_f5_http_backport_service-{{ vip_id }}.json"
      resource_key="name"