---
# tasks file for app role
# ensures the set of containers are running
- docker:
      image: "{{ image_id }}"
      count: "{{ container_cnt }}"
      state: running
      publish_all_ports: True
  tags: 
     - launch_containers
  register: launched_containers

- name: debug var launched containers
  debug: var=launched_containers
  tags: 
     - launch_containers

# - name: Add Pool Members to Dynamic Group to Merge all Pool Members
#   add_host: groups=bigip_pool_members name="{{ item.Config.Hostname }}" ip={{private_ip}} port={{ item.NetworkSettings['Ports']['8000/tcp'][0]['HostPort'] }} description="Name={{item.Name}}, Container Hostname={{item.Config.Hostname}}, Image={{ item.Config.Image }}"
#   with_items: launched_containers.ansible_facts.docker_containers
#   tags:
#     - launch_containers
# 
# - name: Store docker containers from jinja template
#   local_action: template src=../templates/docker_containers.cfg.j2 dest=../cache/{{env_tag}}/{{inventory_hostname}}_docker_containers_just_created
#   tags:
#      - launch_containers