---
# tasks file for app role
# ensures the set of containers are running
- docker:
      name: "hackazon"
      image: "{{ image_id }}"
      count: 1
      ports: 80:80
      command: supervisord -n
      state: running
  tags: 
     - launch_containers
  register: launched_containers
  until: launched_containers["failed"] == false
  retries: 5
  delay: 10

