---
- name: Create Vpc
  cloudformation:
    stack_name="{{ env_name }}-vpc"
    state=present
    region="{{ region }}"
    template={{ project_path }}/roles/infra/files/vpc.json
  args:
    template_parameters:
      cidrBlock: "{{ vpc_cidr }}"
  register: vpc_deploy_results

- name: persist vpc deploy results
  template: src='az-managers.j2' dest='~/vars/{{ env_name }}/inventory/group_vars/az-managers'

