---  
- name: Create subnets in all availability zones
  cloudformation:
    stack_name="{{ env_name }}-az-{{ availability_zone }}"
    state=present
    region="{{ region }}"
    template={{ install_path }}/roles/infra/files/az.json
  args:
    template_parameters:
      vpc: "{{ vpc_id }}"
      internetGateway: "{{ internet_gateway_id }}"
      availabilityZone: "{{ availability_zone }}"
      managementSubnetCidr: "{{ management_cidr }}"
      privateSubnetCidr: "{{ private_cidr }}"
      publicSubnetCidr: "{{ public_cidr }}"
  register: az_deploy_results

- debug: var=az_deploy_results

- name: create a file in which to persist results
  template: src='bigip-managers.j2' dest=~/vars/f5aws/env/{{ env_name }}/inventory/host_vars/{{zone_id}}-bigip1-manager