---
- name: Create Vpc
  cloudformation:
    stack_name="{{ env_name }}-vpc"
    state=present
    region="{{ region }}"
    template={{ project_path }}/roles/infra/files/vpc.json
  args:
    template_parameters:
      cidrBlock: "{{ vpc_cidr }}"
  register: vpc_deploy_results 
  when: vpcId is not defined or (force is defined and force|bool == True)

- debug: var=vpc_deploy_results
  #when: debug is defined and debug|bool == True and force is defined and force|bool ==True

- template: src=infra_vpc.yml.j2 dest=~/vars/{{ env_name }}/infra_vpc.yml
  #when: vpcId is not defined or (force is defined and force|bool == True)