---
- name: Deleting analytics hosts cfn stack(s)
  action: cloudformation
    stack_name="{{ env_name }}-{{ inventory_hostname }}"
    state=absent
    region="{{ region }}"
    template={{ install_path }}/roles/infra/files/analyticshost.json
  register: analytics_teardown_results
  ignore_errors: yes

- copy: content="{{ analytics_teardown_results | to_yaml }}" dest=~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.yml
