---
- name: Teardown vpc
  action: cloudformation
    stack_name="{{ env_name }}-vpc"
    state=absent
    region="{{ region }}"
    template={{ install_path }}/roles/infra/files/vpc.json
  register: vpc_teardown_results
  ignore_errors: yes

- name: debug vpc_teardown_results var 
  debug: var=vpc_teardown_results 

- copy: content="{{ vpc_teardown_results | to_yaml }}" dest=~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.yml
