---

- name: Setup a Pool in a role
  delegate_to: localhost
  bigip_config:
    state=present
    host={{ inventory_hostname }}
    user="{{ bigip_rest_user }}"
    password="{{ bigip_rest_password }}"
    payload="{{json_output.stdout}}"
    collection_path='mgmt/tm/ltm/pool'
    resource_key="name"

