---

- name: Setup a Pool
  delegate_to: localhost
  bigip_config:
    state=present
    host={{ inventory_hostname }}
    user="{{ bigip_rest_user }}"
    password="{{ bigip_rest_pass }}"
    payload="{{ json_payload }}"
    collection_path='/mgmt/tm/ltm/pool'

