---

- name: Setup iApp
  delegate_to: localhost
  bigip_config:
      state=present
      host="{{ inventory_hostname }}"
      user="{{ bigip_rest_user }}"
      password="{{ bigip_rest_pass }}"
      payload='{{demo_iApp|to_nice_json}}'
      collection_path='mgmt/tm/sys/application/service'
      resource_key="name"
