---
- name: Setup the Wideip
  delegate_to: localhost
  bigip_config:
      state=present
      host="{{ inventory_hostname }}"
      user="{{ bigip_rest_user }}"
      password="{{ bigip_rest_pass }}"
      collection_path='mgmt/tm/gtm/wideip'
      resource_key="name"
      payload='{"name":"{{vip_id}}.demo.f5example.com","pools":[{"name":"/Common/{{vip_id}}_pool"}],"poolLbMode":"global-availability"}'


    payload['name'] = name
    members = [ { 'name' : member } for member in pools ]
    payload['pools'] = members
    payload['poolLbMode'] = 'global-availability'
    bigip.post('%s/gtm/wideip' % BIGIP_URL_BASE, data=json.dumps(payload))


