---
# if using Amazon ECS instance, docker should already be installed
# otherwise install docker manually:
# - apt: update_cache=yes
# 
# - name: Install list of packages
#   apt: pkg={{item}} state=installed
#   with_items:
#      - docker
#      - docker.io
#      - python-setuptools
# 
# Install few dependences for ansible
- name: Ensuring 'pip' is available for python package upgrades
  easy_install: name=pip #  puts it nicely in /usr/local/bin/pip

- name: Ensuring 'pip' up to date
  pip: name=pip state=present extra_args='--upgrade' executable=/usr/local/bin/pip

#docker module only compat with version 1.1.0
#https://github.com/ansible/ansible/issues/10879
- name: Ensuring correct version of python 'docker' module
- pip: name=docker-py state=present version=1.1.0 executable=/usr/local/bin/pip

