---
# Since we are installed docker ourselves on our 
# home rolled Ubuntu host, lets be careful to lock down all
# aspects so we don't need to keep testing this stuff...

- name: Ensuring 'pip' is available for python package upgrades
  easy_install: name=pip

- name: Ensuring 'pip' up to date
  pip: name=pip state=present extra_args='--upgrade' executable=/usr/local/bin/pip

# docker ansible module only compat with version 1.1.0
#   See https://github.com/ansible/ansible/issues/10879
- name: Ensuring correct version of python 'docker' module
  pip: name=docker-py state=present version=1.1.0 executable=/usr/local/bin/pip

- name: Make sure apt-get resources are up-to-date
  apt: update_cache=yes

- name: Install docker
  apt: name=docker=1.5-1 state=present force=yes

- name: 
  apt: name=docker.io=1.6.2~dfsg1-1ubuntu4~14.04.1 state=present force=yes