---
- hosts: bigip-managers
  gather_facts: no
  tasks:
    - name: deploy bigips
      include: "{{ install_path }}/roles/infra/tasks/deploy_bigip.yml"


# We need some way to add the management ips to the bigips group
# Unfortunately, the add_hosts directive in ansible does not actually
# execute on a per-host basis within a playbook.  
# Here we solve this problem by looping through JSON results from previous 
# provisioning steps that were by the bigip-managers group (results from bigip provisioning steps)
- hosts: 
   localhost
  gather_facts: no
  tasks:
    - shell: "cat ~/vars/f5aws/env/{{ env_name }}/{{ item }}.json"
      register: output
      with_items: groups['bigip-managers']
      delegate_to: localhost

    - add_host: name="{{ item.stdout | from_json | attr('get')('ManagementInterfacePublicIp') }}" group=bigips
        ExternalInterfacePublicIp="{{ item.stdout | from_json | attr('get')('ExternalInterfacePublicIp') }}"
        ExternalInterfacePrivateIp="{{ item.stdout | from_json | attr('get')('ExternalInterfacePrivateIp') }}"
        InternalInterfacePrivateIp="{{ item.stdout | from_json | attr('get')('InternalInterfacePrivateIp') }}"
      with_items: output['results']

# Need to wait for port 22 to open up
- hosts: bigips
  gather_facts: False
  # vars:
  #   ansible_sudo: True
  tasks:
    - local_action: wait_for host={{ inventory_hostname }} search_regex=OpenSSH delay=10
    - shell: "run /util bash -c 'cat /var/prompt/ps1'"
      until: (result.stdout.find("Active") != -1  or result.stdout.find("NO LICENSE") != -1)
      register: result
      retries: 20

# Basic device setup using tmsh to enable further provisioning
- hosts: bigips
  gather_facts: no
  roles:
    # adds users via tmsh
    - bigip_base 
    # adds json so ansible doesn't puke
    #- bigip_jsonify
    # provisions system globals like ntp, dns, snmp, syslog, db keys  
    - bigip_system
    # sets AWS keys and disables DHCP
    - bigip_system_aws
    # sets vlans, self-ips, routes
    - bigip_network

