---
- hosts: bigips
  gather_facts: no
  vars_files:
  - [ "~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.yml" ]
  tasks:
  - name: Add CFT output variables to host from persisted results from previous playbooks
    set_fact: ansible_ssh_host={{ hostvars[inventory_hostname].stack_outputs.ManagementInterfacePublicIp }}
  - name: Get ltm virtual information
    delegate_to: localhost
    bigip_config:
       state=inspect
       host={{ ansible_ssh_host }}
       user={{ bigip_rest_user }}
       password={{ bigip_rest_password }}
       collection_path='mgmt/tm/ltm/virtual'
    register: result

  - copy: content="{{ result['out'] | to_json }}" dest=~/vars/f5aws/env/{{ env_name }}/facts_{{ inventory_hostname }}.json
    delegate_to: localhost

- hosts: gtms
  gather_facts: no
  vars_files:
  - [ "~/vars/f5aws/env/{{ env_name }}/{{ inventory_hostname }}.yml" ]
  tasks:
  - name: Add CFT output variables to host from persisted results from previous playbooks
    set_fact: ansible_ssh_host={{ hostvars[inventory_hostname].stack_outputs.ManagementInterfacePublicIp }}
  - name: Get ltm wideip information
    delegate_to: localhost
    bigip_config:
       state=inspect
       host={{ ansible_ssh_host }}
       user={{ bigip_rest_user }}
       password={{ bigip_rest_password }}
       collection_path='mgmt/tm/gtm/wideip'
    register: result

  - copy: content="{{ result['out'] | to_json }}" dest=~/vars/f5aws/env/{{ env_name }}/facts_{{ inventory_hostname }}.json
    delegate_to: localhost
  
  
