---
# TODO: playbooks should be idempotent
# PLAY [clienthosts] ************************************************************

# TASK: [Kill Jmeter] ***********************************************************
# failed: [52.5.203.103] => {"changed": true, "cmd": "kill `ps -ef | egrep jmeter | egrep -v egrep | awk '{print $2}'`", "delta": "0:00:00.008302", "end": "2015-07-08 20:22:59.721526", "rc": 2, "start": "2015-07-08 20:22:59.713224", "warnings": []}
# stderr: /bin/sh: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
# kill -l [exitstatus]

# FATAL: all hosts have already failed -- aborting

# PLAY RECAP ********************************************************************
#            to retry, use: --limit @/Users/mutzel/stop_traffic.retry

# 52.5.203.103               : ok=0    changed=0    unreachable=0    failed=1
# localhost                  : ok=2    changed=1    unreachable=0    failed=0
#


# Now that instances created, add its IP to the dynamic clienthosts group
# so we can configure it 
- hosts:
   localhost
  gather_facts: no
  tasks:

    # Re-Create a client host temp group from data persisted to disk
    - shell: "cat ~/vars/f5aws/env/{{ env_name }}/{{ item }}.json"
      register: output
      with_items: groups['clienthost-managers']
      delegate_to: localhost

    - add_host: name="{{ item.stdout | from_json | attr('get')('ClientInstancePublicIp') }}" group=clienthosts
        ClientInstancePublicIp="{{ item.stdout | from_json | attr('get')('ClientInstancePublicIp') }}"
        ClientInstancePrivateIp="{{ item.stdout | from_json | attr('get')('ClientInstancePrivateIp') }}"
        ansible_ssh_user="ubuntu"
      with_items: output['results']

# Upload & launch Jmeter test client in background
- hosts: clienthosts
  gather_facts: False
  tasks:

    - name: Kill Jmeter 
      shell: kill `ps -ef | egrep jmeter | egrep -v egrep | awk '{print $2}'`

   
