# here we make some basic iControlRest calls to setup network elements on BIG-IP
# A more polished implementation might include custom ansible modules for these
# steps.  iCR is used directly for clarity.
---

# get the device hostname

- name: Set the AWS access key and secret key in global-settings
  delegate_to: localhost
  raw: "curl -sk -u {{ bigip_rest_user }}:'{{ bigip_rest_pass }}' -H 'Content-type: application/json' -X PATCH -d '{ \"awsAccessKey\":\"1234\", \"awsSecretKey\":\"1234\" }' https://{{ inventory_hostname }}/mgmt/tm/sys/global-settings"

- name: Stop DHCP
  delegate_to: localhost
  raw: "curl -sk -u {{ bigip_rest_user }}:'{{ bigip_rest_pass }}' -H 'Content-type: application/json' -X PATCH -d '{ \"value\":\"disable\" }' https://{{ inventory_hostname }}/mgmt/tm/sys/db/dhclient.mgmt"

- name: Configure DNS servers
  delegate_to: localhost
  raw: "curl -sk -u {{ bigip_rest_user }}:'{{ bigip_rest_pass }}' -H 'Content-type: application/json' -X PATCH -d '{\"nameServers\":[\"4.2.2.1\"]}' https://{{ inventory_hostname }}/mgmt/tm/sys/dns"

- name: Configure NTP servers
  delegate_to: localhost
  raw: "curl -sk -u {{ bigip_rest_user }}:'{{ bigip_rest_pass }}' -H 'Content-type: application/json' -X PATCH -d '{\"servers\":[\"0.pool.ntp.org\",\"1.pool.ntp.org\"],\"timezone\":\"America/Los_Angeles\"}' https://{{ inventory_hostname }}/mgmt/tm/sys/ntp"

- name: Configure SSH access
  delegate_to: localhost
  raw: "curl -sk -u {{ bigip_rest_user }}:'{{ bigip_rest_pass }}' -H 'Content-type: application/json' -X PATCH -d '{\"allow\":[\"ALL\"]}' https://{{ inventory_hostname }}/mgmt/tm/sys/sshd"

- name: Configure HTTP access 
  delegate_to: localhost
  raw: "curl -sk -u {{ bigip_rest_user }}:'{{ bigip_rest_pass }}' -H 'Content-type: application/json' -X PATCH -d '{\"allow\":[\"ALL\"]}' https://{{ inventory_hostname }}/mgmt/tm/sys/httpd"

- name: Configure SNMP access 
  delegate_to: localhost
  raw: "curl -sk -u {{ bigip_rest_user }}:'{{ bigip_rest_pass }}' -H 'Content-type: application/json' -X PATCH -d '{\"allowedAddresses\":[\"10.0.0.0/255.0.0.0\",\"172.16.0.0/255.255.0.0\"]}' https://{{ inventory_hostname }}/mgmt/tm/sys/snmp"

- name: Configure syslog
  delegate_to: localhost
  raw: "curl -sk -u {{ bigip_rest_user }}:'{{ bigip_rest_pass }}' -H 'Content-type: application/json' -X PATCH -d '{\"include\":\"destination loghost { udp(172.16.3.51 port (514)); udp(172.16.3.52 port (514));};\"}' https://{{ inventory_hostname }}/mgmt/tm/sys/syslog"

