---

# ----------------------------------------------------------------------
# Add GTMs and BIGIPs to the gtm sync group
# ----------------------------------------------------------------------


# 
# - name: Add GTMs to a sync group 
#   bigip_config:
#     state=present
#     host={{ inventory_hostname }}
#     user={{ bigip_rest_user }}
#     password={{ bigip_rest_password }}
#     payload='{"key":"value"}'
#     collection_path='mgmt/tm/util'
# 
# - name: Add BIG-IPs to a sync group 
#   bigip_config:
#     state=present
#     host={{ inventory_hostname }}
#     user={{ bigip_rest_user }}
#     password={{ bigip_rest_password }}
#     payload='{"key":"value"}'
#     collection_path='mgmt/tm/util'
# 
# 

